#!/bin/bash

# hardcode files for now
mkdir -p /run/sshd /root/.ssh /etc/ssh \
    && chmod 700 /root/.ssh \
    && echo 'PermitRootLogin without-password' >> /etc/ssh/sshd_config \
    && echo 'TCPKeepAlive yes' >> /etc/ssh/sshd_config \
    && echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICkFKmtyEjVcYDS1NMK760cn5oLaZNOKRjjOkh0wmRbj' > /root/.ssh/authorized_keys
    
# Run sshd so we can tunnel
/usr/sbin/sshd

# OpenConnect can't handle the new portal; use script to handle auth and pass through VPN Cookie
/vpn_login.sh
