#!/bin/bash

OPENCONNECT_IMG="openconnect:moto"
# Assumes openconnect image is built as $OPENCONNECT_IMG
# Volume mount SSH public key for tunneling to /motoremote.pub
# or directly map /root/.ssh/authorized_keys (with correct permissions)

# Can use sshd as a SOCKS proxy; example SSH config:
#Host motoremote
#    HostName localhost
#    Port 60022
#    User root
#    # Example portforward for internal RDP
#    #LocalForward 3389 cst-rds.sit.mot-solutions.com:3389
#    # SOCKS proxy for accessing internal sites via Firefox
#    DynamicForward 60000
#    IdentityFile ~/.ssh/id_ed25519-motoremote
#
# Can tunnel via motoremote container to internal SSH host; just add:
#    ProxyCommand ssh -q -W %h:%p motoremote
#
# Chrome *may* now work for internal sites; it used to not pass DNS over SOCKS.


docker run -it --rm --cap-add=NET_ADMIN --device /dev/net/tun -p 60022:22 --name motoremote $OPENCONNECT_IMG /mototunnel
